-- Seed the public comparison library (non-onboarding) so Home, Play and
-- Discover feel like a real, populated product from day one. Distributed
-- across all 9 categories with a globally diverse mix of topics.
create temporary table _seed_0008 (
  id uuid not null default gen_random_uuid(),
  category_slug text not null,
  prompt text,
  option_a text not null,
  option_b text not null
) on commit drop;

insert into _seed_0008 (category_slug, prompt, option_a, option_b) values
  ('music', null, 'Drake', 'Kendrick Lamar'),
  ('music', null, 'Beyoncé', 'Rihanna'),
  ('music', null, 'Afrobeats', 'Amapiano'),
  ('music', null, 'Burna Boy', 'Wizkid'),
  ('music', null, 'Taylor Swift', 'Beyoncé'),
  ('music', null, 'Hip-Hop', 'R&B'),
  ('music', null, 'Vinyl', 'Streaming'),
  ('music', null, 'Live concert', 'Music festival'),
  ('music', null, 'Studio album', 'Mixtape'),
  ('music', null, 'The Beatles', 'The Rolling Stones'),
  ('music', null, 'K-pop', 'J-pop'),
  ('music', null, 'BTS', 'BLACKPINK'),
  ('music', null, 'Reggaeton', 'Latin Pop'),
  ('music', null, 'Bad Bunny', 'J Balvin'),
  ('music', null, 'Shakira', 'Karol G'),
  ('music', null, 'Jazz', 'Blues'),
  ('music', null, 'Classical', 'Opera'),
  ('music', null, 'Rock', 'Metal'),
  ('music', null, 'Coldplay', 'Imagine Dragons'),
  ('music', null, 'Ed Sheeran', 'Bruno Mars'),
  ('music', null, 'Adele', 'Sam Smith'),
  ('music', null, 'Old school hip-hop', 'New school hip-hop'),
  ('music', null, 'Fela Kuti', 'Bob Marley'),
  ('music', null, 'Highlife', 'Afrobeats'),
  ('music', null, 'Gospel', 'Soul'),
  ('music', null, 'Country', 'Folk'),
  ('music', null, 'EDM', 'House'),
  ('music', null, 'Techno', 'Trance'),
  ('music', null, 'Davido', 'Wizkid'),
  ('music', null, 'Tems', 'Ayra Starr'),
  ('music', null, 'Eminem', 'Jay-Z'),
  ('music', null, '50 Cent', 'Nas'),
  ('music', null, 'Frank Ocean', 'The Weeknd'),
  ('music', null, 'Rihanna', 'Nicki Minaj'),
  ('music', null, 'Cardi B', 'Megan Thee Stallion'),
  ('music', null, 'Spotify', 'Apple Music'),
  ('music', null, 'YouTube Music', 'SoundCloud'),
  ('music', null, 'Headphones', 'Speakers'),
  ('music', null, 'Karaoke night', 'Silent listening'),
  ('music', null, 'Singing in the shower', 'Singing in the car'),
  ('music', null, 'Album on release day', 'Wait for the hype'),
  ('music', null, 'Lyrics first', 'Melody first'),
  ('music', null, 'Sad songs', 'Happy songs'),
  ('music', null, 'Slow ballads', 'High energy anthems'),
  ('music', null, 'Music videos', 'Lyric videos'),
  ('music', null, 'Legendary one-hit wonder', 'Consistent hitmaker'),
  ('music', null, 'Mariah Carey', 'Whitney Houston'),
  ('music', null, 'Michael Jackson', 'Prince'),
  ('music', null, 'Kanye West', 'Travis Scott'),
  ('music', null, 'Playboi Carti', 'Lil Uzi Vert'),
  ('music', null, 'SZA', 'Summer Walker'),
  ('music', null, 'Dancehall', 'Reggae'),
  ('music', null, 'Bollywood soundtracks', 'Punjabi pop'),
  ('music', null, 'Arijit Singh', 'A.R. Rahman'),
  ('music', null, 'Angélique Kidjo', 'Youssou N''Dour'),
  ('music', null, 'Manu Chao', 'Buena Vista Social Club'),
  ('music', null, 'Daft Punk', 'Justice'),
  ('music', null, 'David Guetta', 'Calvin Harris'),
  ('music', null, 'Music theory nerd', 'Pure vibes listener'),
  ('music', null, 'Concert front row', 'Chill in the back'),
  ('music', null, 'Band merch', 'Just the music'),
  ('music', null, 'Playlist curator', 'Shuffle everything'),
  ('music', null, 'Guitar', 'Piano'),
  ('music', null, 'Drums', 'Bass'),
  ('music', null, 'Acoustic set', 'Full production'),
  ('music', null, 'Remix', 'Original'),
  ('music', null, 'Collab track', 'Solo artist'),
  ('music', null, 'Freestyle rap', 'Written verses'),
  ('music', null, '90s R&B', '2000s R&B'),
  ('music', null, 'Nostalgia playlist', 'Discover Weekly'),
  ('music', null, 'Big stadium tour', 'Intimate venue show'),
  ('music', null, 'Grammy winner', 'Underground favorite'),
  ('music', null, 'Songwriter', 'Producer'),
  ('music', null, 'Christmas music in November', 'Never before December'),
  ('music', null, 'Podcasts', 'Music'),
  ('music', null, 'Amapiano log drum', 'Afrobeats groove'),
  ('music', null, 'Stormzy', 'Dave'),
  ('music', null, 'UK Drill', 'US Drill'),
  ('music', null, 'Central Cee', 'Skepta'),
  ('music', null, 'Coachella', 'Glastonbury'),
  ('music', null, 'Rock ballad', 'Pop anthem'),
  ('music', null, 'Vinyl crackle', 'Studio-clean audio'),
  ('music', null, 'Long album', 'Tight EP'),
  ('cars', null, 'BMW', 'Mercedes-Benz'),
  ('cars', null, 'Toyota', 'Honda'),
  ('cars', null, 'Ferrari', 'Lamborghini'),
  ('cars', null, 'Porsche', 'Ferrari'),
  ('cars', null, 'Tesla', 'Rivian'),
  ('cars', null, 'Electric', 'Petrol'),
  ('cars', null, 'Manual transmission', 'Automatic transmission'),
  ('cars', null, 'Sports car', 'SUV'),
  ('cars', null, 'Sedan', 'Hatchback'),
  ('cars', null, 'Pickup truck', 'SUV'),
  ('cars', null, 'Convertible', 'Coupe'),
  ('cars', null, 'Audi', 'BMW'),
  ('cars', null, 'Range Rover', 'Toyota Land Cruiser'),
  ('cars', null, 'Ford Mustang', 'Chevrolet Camaro'),
  ('cars', null, 'Jeep', 'Land Rover'),
  ('cars', null, 'Volkswagen', 'Volvo'),
  ('cars', null, 'Lexus', 'Infiniti'),
  ('cars', null, 'Bugatti', 'Koenigsegg'),
  ('cars', null, 'Rolls-Royce', 'Bentley'),
  ('cars', null, 'Old classic car', 'Brand new model'),
  ('cars', null, 'Self-driving', 'Full manual control'),
  ('cars', null, 'Matte finish', 'Glossy finish'),
  ('cars', null, 'Leather interior', 'Alcantara interior'),
  ('cars', null, 'Big spoiler', 'Clean minimal look'),
  ('cars', null, 'Loud exhaust', 'Silent electric'),
  ('cars', null, 'Track day', 'Sunday cruise'),
  ('cars', null, 'Own a car', 'Rely on ride-hailing'),
  ('cars', null, 'Driving stick', 'Automatic ease'),
  ('cars', null, 'Motorbike', 'Car'),
  ('cars', null, 'Road trip', 'Flying'),
  ('cars', null, 'Formula 1', 'MotoGP'),
  ('cars', null, 'Lewis Hamilton', 'Max Verstappen'),
  ('cars', null, 'Ferrari F1', 'Red Bull Racing'),
  ('cars', null, 'Off-road capability', 'City handling'),
  ('cars', null, 'Hybrid', 'Fully electric'),
  ('cars', null, 'Big V8 engine', 'Efficient turbo four'),
  ('cars', null, 'Custom rims', 'Factory stock'),
  ('cars', null, 'Car wash weekly', 'Whenever it looks dirty'),
  ('cars', null, 'Wash it yourself', 'Take it to a car wash'),
  ('cars', null, 'New car smell', 'Broken-in comfort'),
  ('cars', null, 'Dashcam', 'No dashcam'),
  ('cars', null, 'Buy new', 'Buy used'),
  ('cars', null, 'Lease', 'Own outright'),
  ('cars', null, 'Mini Cooper', 'Fiat 500'),
  ('cars', null, 'Subaru WRX', 'Mitsubishi Evo'),
  ('cars', null, 'Nissan GT-R', 'Toyota Supra'),
  ('cars', null, 'Hyundai', 'Kia'),
  ('cars', null, 'Mazda', 'Honda'),
  ('cars', null, 'Big rims', 'All-terrain tires'),
  ('cars', null, 'Sunroof', 'No sunroof'),
  ('cars', null, 'Heated seats', 'Cooled seats'),
  ('cars', null, 'Parking sensors', 'Backup camera only'),
  ('cars', null, 'Wireless CarPlay', 'Wired CarPlay'),
  ('cars', null, 'Big touchscreen', 'Physical buttons'),
  ('cars', null, 'Fast charging', 'Long range battery'),
  ('cars', null, 'Gas station stop', 'Home charging'),
  ('cars', null, 'City car', 'Highway cruiser'),
  ('cars', null, 'Rally racing', 'Drag racing'),
  ('cars', null, 'Car meets', 'Solo drives'),
  ('cars', null, 'Wax it by hand', 'Ceramic coating'),
  ('cars', null, 'American muscle', 'Japanese tuner'),
  ('cars', null, 'German engineering', 'Italian design'),
  ('cars', null, 'Danfo bus nostalgia', 'Modern ride-share'),
  ('cars', null, 'Camry reliability', 'Accord reliability'),
  ('cars', null, 'Compact car for parking', 'Big car for comfort'),
  ('cars', null, 'Buy the base model', 'Load up on options'),
  ('cars', null, 'Take the scenic route', 'Take the fastest route'),
  ('cars', null, 'Roof rack for gear', 'Keep it clean'),
  ('cars', null, 'Tinted windows', 'Clear windows'),
  ('cars', null, 'Aftermarket sound system', 'Stock speakers'),
  ('cars', null, 'Drive-in movie', 'Regular cinema'),
  ('cars', null, 'Racing video games', 'Real track days'),
  ('cars', null, 'Volkswagen Golf', 'Ford Focus'),
  ('cars', null, 'Electric scooter', 'Bicycle'),
  ('cars', null, 'Public transit', 'Own car'),
  ('cars', null, 'Chauffeur', 'Drive yourself'),
  ('cars', null, 'Classic Beetle', 'Classic Mustang'),
  ('cars', null, 'Car detailing obsessive', 'Function over form'),
  ('cars', null, 'Big engine sound', 'Whisper-quiet ride'),
  ('fashion', null, 'Nike', 'Adidas'),
  ('fashion', null, 'Streetwear', 'Formal wear'),
  ('fashion', null, 'Sneakers', 'Boots'),
  ('fashion', null, 'Minimalist', 'Bold and loud'),
  ('fashion', null, 'Gucci', 'Louis Vuitton'),
  ('fashion', null, 'Off-White', 'Supreme'),
  ('fashion', null, 'Vintage thrift', 'Brand new'),
  ('fashion', null, 'High fashion', 'Everyday casual'),
  ('fashion', null, 'Jordans', 'Yeezys'),
  ('fashion', null, 'Designer bag', 'Practical backpack'),
  ('fashion', null, 'Bold prints', 'Solid colors'),
  ('fashion', null, 'Statement jewelry', 'Understated jewelry'),
  ('fashion', null, 'Baggy fits', 'Slim fits'),
  ('fashion', null, 'Ankara prints', 'Western formal wear'),
  ('fashion', null, 'Agbada', 'Suit and tie'),
  ('fashion', null, 'Hoodie and joggers', 'Blazer and slacks'),
  ('fashion', null, 'Custom tailored', 'Off the rack'),
  ('fashion', null, 'Chanel', 'Dior'),
  ('fashion', null, 'Balenciaga', 'Versace'),
  ('fashion', null, 'Zara', 'H&M'),
  ('fashion', null, 'Fast fashion', 'Slow fashion'),
  ('fashion', null, 'Y2K style', '90s grunge'),
  ('fashion', null, 'Cottagecore', 'Streetwear'),
  ('fashion', null, 'Monochrome outfit', 'Colorful outfit'),
  ('fashion', null, 'Statement sneakers', 'Classic loafers'),
  ('fashion', null, 'Bucket hat', 'Snapback'),
  ('fashion', null, 'Gold jewelry', 'Silver jewelry'),
  ('fashion', null, 'Long nails', 'Natural nails'),
  ('fashion', null, 'Bold makeup', 'Natural makeup'),
  ('fashion', null, 'Skincare routine', 'Wing it'),
  ('fashion', null, 'Perfume', 'Cologne'),
  ('fashion', null, 'Handmade jewelry', 'Luxury brand jewelry'),
  ('fashion', null, 'Crocs', 'Flip-flops'),
  ('fashion', null, 'High heels', 'Flats'),
  ('fashion', null, 'Denim jacket', 'Leather jacket'),
  ('fashion', null, 'Oversized fit', 'Fitted silhouette'),
  ('fashion', null, 'Beanie', 'Cap'),
  ('fashion', null, 'Print tee', 'Plain tee'),
  ('fashion', null, 'Statement coat', 'Classic trench'),
  ('fashion', null, 'Iro and buba', 'Kaftan'),
  ('fashion', null, 'Dashiki', 'Suit'),
  ('fashion', null, 'Sari', 'Lehenga'),
  ('fashion', null, 'Kimono', 'Hanbok'),
  ('fashion', null, 'Athleisure', 'Business casual'),
  ('fashion', null, 'Bold sunglasses', 'Classic aviators'),
  ('fashion', null, 'Layering', 'One clean piece'),
  ('fashion', null, 'Bright colors', 'All black everything'),
  ('fashion', null, 'Handbags', 'Backpacks'),
  ('fashion', null, 'Custom sneaker paint job', 'Fresh out the box'),
  ('fashion', null, 'Match your outfit to your partner', 'Dress independently'),
  ('fashion', null, 'Shop online', 'Shop in-store'),
  ('fashion', null, 'New drop hype', 'Timeless classics'),
  ('fashion', null, 'Puma', 'Under Armour'),
  ('fashion', null, 'New Balance', 'Asics'),
  ('fashion', null, 'Retro Jordans', 'New Jordan releases'),
  ('fashion', null, 'Watches', 'Bracelets'),
  ('fashion', null, 'Rings', 'Necklaces'),
  ('fashion', null, 'Second-hand luxury', 'New mid-range'),
  ('fashion', null, 'Comfort over style', 'Style over comfort'),
  ('fashion', null, 'Capsule wardrobe', 'Ever-growing closet'),
  ('fashion', null, 'Matching sets', 'Mix and match'),
  ('fashion', null, 'Belt bag', 'Tote bag'),
  ('fashion', null, 'Graphic hoodie', 'Plain hoodie'),
  ('fashion', null, 'Barber fresh cut', 'Grow it out'),
  ('fashion', null, 'Locs', 'Braids'),
  ('fashion', null, 'Natural hair', 'Wigs and extensions'),
  ('fashion', null, 'Tattoos', 'No tattoos'),
  ('fashion', null, 'Piercings', 'No piercings'),
  ('fashion', null, 'Custom fragrance', 'Designer fragrance'),
  ('fashion', null, 'Shop the sale rack', 'Full price for the piece you want'),
  ('fashion', null, 'Runway trends', 'Personal style'),
  ('fashion', null, 'Vintage band tee', 'New merch drop'),
  ('fashion', null, 'Socks and sandals', 'Never socks with sandals'),
  ('fashion', null, 'Bold tracksuit', 'Neutral tracksuit'),
  ('fashion', null, 'Statement earrings', 'No earrings'),
  ('fashion', null, 'Silk scarf', 'Baseball cap'),
  ('fashion', null, 'Trendy sunglasses', 'Prescription glasses as a look'),
  ('travel', null, 'Beach', 'City'),
  ('travel', null, 'Mountains', 'Ocean'),
  ('travel', null, 'Luxury resort', 'Backpacking'),
  ('travel', null, 'Barcelona', 'Miami'),
  ('travel', null, 'Lagos', 'Abuja'),
  ('travel', null, 'Paris', 'Rome'),
  ('travel', null, 'Tokyo', 'Seoul'),
  ('travel', null, 'Dubai', 'Doha'),
  ('travel', null, 'New York City', 'Los Angeles'),
  ('travel', null, 'London', 'Amsterdam'),
  ('travel', null, 'Cape Town', 'Nairobi'),
  ('travel', null, 'Rio de Janeiro', 'Buenos Aires'),
  ('travel', null, 'Bali', 'Phuket'),
  ('travel', null, 'Cairo', 'Marrakech'),
  ('travel', null, 'Window seat', 'Aisle seat'),
  ('travel', null, 'Road trip', 'Flight'),
  ('travel', null, 'Solo travel', 'Group travel'),
  ('travel', null, 'All-inclusive resort', 'Airbnb local stay'),
  ('travel', null, 'Plan every detail', 'Wing it'),
  ('travel', null, 'Carry-on only', 'Check a bag'),
  ('travel', null, 'Mountains for hiking', 'Beach for relaxing'),
  ('travel', null, 'Cold winter destination', 'Hot summer destination'),
  ('travel', null, 'Street food', 'Fine dining while traveling'),
  ('travel', null, 'Tourist landmarks', 'Hidden local spots'),
  ('travel', null, 'City break', 'Nature retreat'),
  ('travel', null, 'Nairobi safari', 'Cape Town coastline'),
  ('travel', null, 'Accra', 'Lagos'),
  ('travel', null, 'Johannesburg', 'Cape Town'),
  ('travel', null, 'Istanbul', 'Athens'),
  ('travel', null, 'Bangkok', 'Singapore'),
  ('travel', null, 'Hong Kong', 'Shanghai'),
  ('travel', null, 'Mumbai', 'Delhi'),
  ('travel', null, 'Mexico City', 'Cancún'),
  ('travel', null, 'Toronto', 'Vancouver'),
  ('travel', null, 'Sydney', 'Melbourne'),
  ('travel', null, 'Iceland''s landscapes', 'Switzerland''s Alps'),
  ('travel', null, 'Camping under the stars', 'Hotel room comfort'),
  ('travel', null, 'Cruise ship', 'Backpacking trail'),
  ('travel', null, 'Travel with a guidebook', 'Travel with just Google Maps'),
  ('travel', null, 'Souvenirs', 'Photos as memories'),
  ('travel', null, 'Business class', 'Save money, fly economy'),
  ('travel', null, 'Long layover, cheaper flight', 'Direct flight, pricier'),
  ('travel', null, 'Passport stamps collector', 'Repeat your favorite place'),
  ('travel', null, 'New country every year', 'Deep dive one region'),
  ('travel', null, 'Rainforest trek', 'Desert safari'),
  ('travel', null, 'Northern lights', 'Great Barrier Reef'),
  ('travel', null, 'Sahara Desert', 'Amazon Rainforest'),
  ('travel', null, 'Kilimanjaro climb', 'Everest base camp'),
  ('travel', null, 'Local market haggling', 'Fixed-price shopping'),
  ('travel', null, 'Learn the language first', 'Point and gesture'),
  ('travel', null, 'Travel insurance always', 'Risk it'),
  ('travel', null, 'Digital nomad life', 'Home base with vacations'),
  ('travel', null, 'Weekend getaway', 'Two-week trip'),
  ('travel', null, 'Beach club', 'Quiet cove'),
  ('travel', null, 'Historic old town', 'Modern skyline'),
  ('travel', null, 'Public transit abroad', 'Rent a car abroad'),
  ('travel', null, 'Street markets', 'Shopping malls'),
  ('travel', null, 'Hostel vibes', 'Hotel privacy'),
  ('travel', null, 'Sunrise hike', 'Sunset views'),
  ('travel', null, 'Snorkeling', 'Scuba diving'),
  ('travel', null, 'Ski resort', 'Beach resort'),
  ('travel', null, 'Van life', 'City apartment stays'),
  ('travel', null, 'Pack light', 'Pack for every scenario'),
  ('travel', null, 'Travel during peak season', 'Travel off-season'),
  ('travel', null, 'Visit friends abroad', 'Explore somewhere new'),
  ('travel', null, 'Guided tour', 'Explore on your own'),
  ('travel', null, 'Local street food stalls', 'Michelin-starred restaurant'),
  ('travel', null, 'Volunteering abroad', 'Pure leisure travel'),
  ('travel', null, 'Long weekend trips', 'One big annual trip'),
  ('travel', null, 'Overpack the camera gear', 'Just use your phone'),
  ('travel', null, 'Travel journal', 'Just live in the moment'),
  ('gaming', null, 'PlayStation', 'Xbox'),
  ('gaming', null, 'PC gaming', 'Console gaming'),
  ('gaming', null, 'Nintendo Switch', 'Steam Deck'),
  ('gaming', null, 'Single-player', 'Multiplayer'),
  ('gaming', null, 'Mobile gaming', 'Handheld console'),
  ('gaming', null, 'FIFA', 'PES / eFootball'),
  ('gaming', null, 'Call of Duty', 'Battlefield'),
  ('gaming', null, 'Fortnite', 'Apex Legends'),
  ('gaming', null, 'Minecraft', 'Roblox'),
  ('gaming', null, 'League of Legends', 'Dota 2'),
  ('gaming', null, 'Valorant', 'CS2'),
  ('gaming', null, 'Grand Theft Auto', 'Red Dead Redemption'),
  ('gaming', null, 'The Legend of Zelda', 'Final Fantasy'),
  ('gaming', null, 'God of War', 'The Last of Us'),
  ('gaming', null, 'Elden Ring', 'Dark Souls'),
  ('gaming', null, 'Overwatch', 'Rainbow Six Siege'),
  ('gaming', null, 'Mario Kart', 'Crash Team Racing'),
  ('gaming', null, 'Retro games', 'Modern AAA titles'),
  ('gaming', null, 'Story-driven games', 'Competitive multiplayer'),
  ('gaming', null, 'Open world', 'Linear campaign'),
  ('gaming', null, 'Controller', 'Keyboard and mouse'),
  ('gaming', null, 'Ranked matches', 'Casual matches'),
  ('gaming', null, 'Speedrunning', '100% completion'),
  ('gaming', null, 'Physical game discs', 'Digital downloads'),
  ('gaming', null, 'Cloud gaming', 'Local hardware'),
  ('gaming', null, 'Esports fan', 'Casual gamer'),
  ('gaming', null, 'Twitch streaming', 'YouTube gaming videos'),
  ('gaming', null, 'Play to relax', 'Play to compete'),
  ('gaming', null, 'Co-op with friends', 'Solo campaign'),
  ('gaming', null, 'Horror games', 'Puzzle games'),
  ('gaming', null, 'Turn-based strategy', 'Real-time action'),
  ('gaming', null, 'Pokémon', 'Digimon'),
  ('gaming', null, 'Genshin Impact', 'Honkai: Star Rail'),
  ('gaming', null, 'Among Us', 'Fall Guys'),
  ('gaming', null, 'Animal Crossing', 'Stardew Valley'),
  ('gaming', null, 'Cyberpunk 2077', 'Starfield'),
  ('gaming', null, 'Halo', 'Gears of War'),
  ('gaming', null, 'Street Fighter', 'Mortal Kombat'),
  ('gaming', null, 'Tekken', 'Super Smash Bros.'),
  ('gaming', null, 'Chess online', 'Board games in person'),
  ('gaming', null, 'New console at launch', 'Wait for a price drop'),
  ('gaming', null, 'Splitscreen couch co-op', 'Online co-op'),
  ('gaming', null, 'Building your own PC', 'Buying pre-built'),
  ('gaming', null, 'RGB lighting setup', 'Clean minimal setup'),
  ('gaming', null, 'Game soundtrack on repeat', 'Ambient in-game only'),
  ('gaming', null, 'Spend on skins', 'Never spend on cosmetics'),
  ('gaming', null, 'Season pass buyer', 'Wait for the complete edition'),
  ('gaming', null, 'Difficulty on hard', 'Difficulty on normal'),
  ('gaming', null, 'Achievements hunter', 'Just enjoy the ride'),
  ('gaming', null, 'Mobile gacha games', 'Premium mobile titles'),
  ('gaming', null, 'LAN party nostalgia', 'Online matchmaking'),
  ('gaming', null, 'Boss rush mode', 'Exploration mode'),
  ('gaming', null, 'Indie games', 'Big studio blockbusters'),
  ('gaming', null, 'Roguelike runs', 'Save-and-continue games'),
  ('gaming', null, 'VR gaming', 'Flat screen gaming'),
  ('gaming', null, 'Racing sims', 'Arcade racers'),
  ('gaming', null, 'Sports games', 'Fighting games'),
  ('gaming', null, 'Sandbox creativity', 'Structured objectives'),
  ('sports', null, 'Messi', 'Ronaldo'),
  ('sports', null, 'Football', 'Basketball'),
  ('sports', null, 'Real Madrid', 'Barcelona'),
  ('sports', null, 'Manchester United', 'Manchester City'),
  ('sports', null, 'Liverpool', 'Chelsea'),
  ('sports', null, 'Arsenal', 'Tottenham'),
  ('sports', null, 'NBA', 'Premier League'),
  ('sports', null, 'LeBron James', 'Michael Jordan'),
  ('sports', null, 'Kobe Bryant', 'LeBron James'),
  ('sports', null, 'Serena Williams', 'Venus Williams'),
  ('sports', null, 'Usain Bolt', 'Michael Johnson'),
  ('sports', null, 'Boxing', 'MMA'),
  ('sports', null, 'Cricket', 'Rugby'),
  ('sports', null, 'Watching live at the stadium', 'Watching on TV'),
  ('sports', null, 'Team sport', 'Individual sport'),
  ('sports', null, 'Home team loyalty', 'Follow the best players'),
  ('sports', null, 'Formula 1', 'Football'),
  ('sports', null, 'Olympics', 'World Cup'),
  ('sports', null, 'Tennis', 'Golf'),
  ('sports', null, 'Swimming', 'Athletics'),
  ('sports', null, 'Basketball street courts', 'Indoor gym league'),
  ('sports', null, 'College sports', 'Professional sports'),
  ('sports', null, 'Fantasy football', 'Just watch for fun'),
  ('sports', null, 'Sports betting', 'Watch without betting'),
  ('sports', null, 'Home jersey', 'Away jersey'),
  ('sports', null, 'Pelé', 'Maradona'),
  ('sports', null, 'Neymar', 'Mbappé'),
  ('sports', null, 'Haaland', 'Mbappé'),
  ('sports', null, 'Drogba', 'Henry'),
  ('sports', null, 'African football stars', 'European football stars'),
  ('sports', null, 'Nigeria''s Super Eagles', 'Ghana''s Black Stars'),
  ('sports', null, 'Senegal', 'Ivory Coast'),
  ('sports', null, 'Wrestling (WWE)', 'Boxing'),
  ('sports', null, 'UFC', 'Boxing'),
  ('sports', null, 'Cycling', 'Running'),
  ('sports', null, 'Gym workouts', 'Outdoor sports'),
  ('sports', null, 'Marathon running', 'Sprinting'),
  ('sports', null, 'Table tennis', 'Badminton'),
  ('sports', null, 'Volleyball', 'Handball'),
  ('sports', null, 'Playing sports', 'Watching sports'),
  ('sports', null, 'Sunday league football', 'Watching the pros'),
  ('sports', null, 'Home advantage', 'Underdog upset'),
  ('sports', null, 'Penalty shootout drama', 'Clean 90-minute win'),
  ('sports', null, 'Derby day rivalry', 'Regular season match'),
  ('sports', null, 'Sports documentaries', 'Live match highlights'),
  ('sports', null, 'Coach''s tactics', 'Individual brilliance'),
  ('sports', null, 'Youth academies', 'Big transfer signings'),
  ('sports', null, 'National team pride', 'Club team loyalty'),
  ('sports', null, 'Cristiano''s dedication', 'Messi''s flair'),
  ('sports', null, 'American football', 'Rugby'),
  ('sports', null, 'Baseball', 'Cricket'),
  ('sports', null, 'Ice hockey', 'Field hockey'),
  ('sports', null, 'Skateboarding', 'Surfing'),
  ('sports', null, 'Snowboarding', 'Skiing'),
  ('sports', null, 'Climbing', 'Hiking'),
  ('sports', null, 'Darts', 'Snooker'),
  ('sports', null, 'Chess as a sport', 'Esports as a sport'),
  ('sports', null, 'Sports podcasts', 'Sports talk shows'),
  ('sports', null, 'Practice alone', 'Train with a team'),
  ('sports', null, 'Big-name transfer window drama', 'Quiet consistent squad building'),
  ('food', null, 'Pizza', 'Burger'),
  ('food', null, 'Spicy', 'Mild'),
  ('food', null, 'Home cooked', 'Takeout'),
  ('food', null, 'Sweet', 'Savory'),
  ('food', null, 'Jollof rice', 'Fried rice'),
  ('food', null, 'Nigerian jollof', 'Ghanaian jollof'),
  ('food', null, 'Suya', 'Kebab'),
  ('food', null, 'Pounded yam', 'Eba'),
  ('food', null, 'Egusi soup', 'Okra soup'),
  ('food', null, 'Tacos', 'Burritos'),
  ('food', null, 'Ramen', 'Pho'),
  ('food', null, 'Sushi', 'Sashimi'),
  ('food', null, 'Pasta', 'Rice'),
  ('food', null, 'Indian curry', 'Thai curry'),
  ('food', null, 'Butter chicken', 'Chicken tikka masala'),
  ('food', null, 'Croissant', 'Bagel'),
  ('food', null, 'Coffee', 'Tea'),
  ('food', null, 'Espresso', 'Filter coffee'),
  ('food', null, 'Milk chocolate', 'Dark chocolate'),
  ('food', null, 'Ice cream', 'Cake'),
  ('food', null, 'Fried chicken', 'Grilled chicken'),
  ('food', null, 'Jollof from a party', 'Home-made jollof'),
  ('food', null, 'Street food', 'Restaurant dining'),
  ('food', null, 'Breakfast for dinner', 'Dinner for breakfast'),
  ('food', null, 'Big breakfast', 'Skip breakfast'),
  ('food', null, 'Cook from scratch', 'Meal kits'),
  ('food', null, 'Fast food', 'Slow-cooked meals'),
  ('food', null, 'Shawarma', 'Suya'),
  ('food', null, 'Plantain', 'Yam'),
  ('food', null, 'Rice and stew', 'Amala and ewedu'),
  ('food', null, 'Meat pie', 'Sausage roll'),
  ('food', null, 'Chin chin', 'Puff puff'),
  ('food', null, 'Moin moin', 'Akara'),
  ('food', null, 'Peppered snail', 'Peppered goat meat'),
  ('food', null, 'Palm wine', 'Zobo'),
  ('food', null, 'Kunu', 'Fura da nono'),
  ('food', null, 'BBQ', 'Grilled fish'),
  ('food', null, 'Pizza from scratch', 'Delivery pizza'),
  ('food', null, 'Deep dish pizza', 'Thin crust pizza'),
  ('food', null, 'Pineapple on pizza', 'No pineapple on pizza'),
  ('food', null, 'Vegetarian', 'Meat lover'),
  ('food', null, 'Vegan', 'Dairy lover'),
  ('food', null, 'Street tacos', 'Sit-down Mexican restaurant'),
  ('food', null, 'Wine', 'Beer'),
  ('food', null, 'Cocktails', 'Straight spirits'),
  ('food', null, 'Smoothies', 'Fresh juice'),
  ('food', null, 'Cereal', 'Oatmeal'),
  ('food', null, 'Pancakes', 'Waffles'),
  ('food', null, 'French fries', 'Onion rings'),
  ('food', null, 'Ketchup', 'Mayo'),
  ('food', null, 'Extra spicy pepper sauce', 'Mild seasoning'),
  ('food', null, 'Buffet', 'À la carte'),
  ('food', null, 'Grocery shopping weekly', 'Grab what you need daily'),
  ('food', null, 'Cook with recipes', 'Cook by instinct'),
  ('food', null, 'Baking', 'Grilling'),
  ('food', null, 'Late night snacks', 'No eating after 8pm'),
  ('food', null, 'Cheese lover', 'Not a cheese person'),
  ('food', null, 'Big Sunday feast', 'Simple everyday meals'),
  ('food', null, 'Nando''s', 'KFC'),
  ('food', null, 'Domino''s', 'Local pizzeria'),
  ('food', null, 'Boba tea', 'Fresh coconut water'),
  ('food', null, 'Mango', 'Pineapple'),
  ('food', null, 'Avocado toast', 'Peanut butter toast'),
  ('food', null, 'Grilled fish and plantain', 'Rice and chicken'),
  ('food', null, 'Homemade jollof at a party', 'Caterer''s jollof'),
  ('food', null, 'Puff-puff on the street', 'Donuts from a bakery'),
  ('food', null, 'Local market produce', 'Supermarket produce'),
  ('food', null, 'Eating with hands', 'Eating with cutlery'),
  ('movies', null, 'Marvel', 'DC'),
  ('movies', null, 'Cinema', 'Streaming at home'),
  ('movies', null, 'Comedy', 'Drama'),
  ('movies', null, 'Sequel', 'Original'),
  ('movies', null, 'Batman', 'Superman'),
  ('movies', null, 'Star Wars', 'Star Trek'),
  ('movies', null, 'Harry Potter', 'Lord of the Rings'),
  ('movies', null, 'Fast & Furious', 'Mission Impossible'),
  ('movies', null, 'Horror movies', 'Comedy movies'),
  ('movies', null, 'Romantic comedy', 'Action thriller'),
  ('movies', null, 'Nollywood', 'Bollywood'),
  ('movies', null, 'Nollywood', 'Hollywood'),
  ('movies', null, 'Netflix', 'Disney+'),
  ('movies', null, 'HBO Max', 'Amazon Prime Video'),
  ('movies', null, 'Christopher Nolan films', 'Quentin Tarantino films'),
  ('movies', null, 'Marvel Cinematic Universe', 'DC Extended Universe'),
  ('movies', null, 'Spider-Man', 'Batman'),
  ('movies', null, 'The Godfather', 'Scarface'),
  ('movies', null, 'Titanic', 'Avatar'),
  ('movies', null, 'Inception', 'Interstellar'),
  ('movies', null, 'The Dark Knight', 'Joker'),
  ('movies', null, 'Anime', 'Cartoons'),
  ('movies', null, 'Studio Ghibli', 'Pixar'),
  ('movies', null, 'Naruto', 'One Piece'),
  ('movies', null, 'Dragon Ball Z', 'My Hero Academia'),
  ('movies', null, 'Binge-watch a series', 'Watch one episode a week'),
  ('movies', null, 'Subtitles', 'Dubbed'),
  ('movies', null, 'Movie theater popcorn', 'Snacks from home'),
  ('movies', null, '3D movies', 'Regular screening'),
  ('movies', null, 'Documentaries', 'Fiction films'),
  ('movies', null, 'True crime', 'Fantasy'),
  ('movies', null, 'Rom-com ending', 'Twist ending'),
  ('movies', null, 'Watch trailers before', 'Go in blind'),
  ('movies', null, 'Rewatch your favorite', 'Always something new'),
  ('movies', null, 'Book first, then movie', 'Movie first, then book'),
  ('movies', null, 'Long epic movies', 'Quick 90-minute films'),
  ('movies', null, 'Tom Cruise action', 'Keanu Reeves action'),
  ('movies', null, 'Denzel Washington', 'Will Smith'),
  ('movies', null, 'Leonardo DiCaprio', 'Brad Pitt'),
  ('movies', null, 'Meryl Streep', 'Viola Davis'),
  ('movies', null, 'Genevieve Nnaji', 'Funke Akindele'),
  ('movies', null, 'Ryan Reynolds humor', 'Kevin Hart humor'),
  ('movies', null, 'Slow-burn thriller', 'Fast-paced action'),
  ('movies', null, 'Musicals', 'Straight drama'),
  ('movies', null, 'Animated films', 'Live action'),
  ('movies', null, 'Prequels', 'Sequels'),
  ('movies', null, 'Cinematic universe', 'Standalone film'),
  ('movies', null, 'Award-winning indie film', 'Blockbuster hit'),
  ('movies', null, 'Watch alone', 'Watch with friends'),
  ('movies', null, 'Movie night at home', 'Trip to the cinema'),
  ('movies', null, 'Cliffhanger ending', 'Full resolution'),
  ('movies', null, 'Villain steals the show', 'Hero steals the show'),
  ('movies', null, 'Practical effects', 'CGI'),
  ('movies', null, 'Remake', 'Original classic'),
  ('movies', null, 'James Bond', 'Jason Bourne'),
  ('movies', null, 'The Matrix', 'Inception'),
  ('movies', null, 'Squid Game', 'Money Heist'),
  ('movies', null, 'K-dramas', 'Turkish dramas'),
  ('movies', null, 'Telenovelas', 'Nollywood dramas'),
  ('movies', null, 'Superhero movies', 'Space epics'),
  ('technology', null, 'iPhone', 'Samsung'),
  ('technology', null, 'Mac', 'Windows'),
  ('technology', null, 'Android', 'iOS'),
  ('technology', null, 'Wired earphones', 'Wireless earbuds'),
  ('technology', null, 'AirPods', 'Galaxy Buds'),
  ('technology', null, 'AI', 'Traditional software'),
  ('technology', null, 'ChatGPT', 'Google Gemini'),
  ('technology', null, 'Claude', 'ChatGPT'),
  ('technology', null, 'Laptop', 'Desktop'),
  ('technology', null, 'Tablet', 'Laptop'),
  ('technology', null, 'PlayStation VR', 'Meta Quest'),
  ('technology', null, 'Smartwatch', 'Classic watch'),
  ('technology', null, 'Apple Watch', 'Garmin'),
  ('technology', null, 'Physical keyboard', 'Touchscreen keyboard'),
  ('technology', null, 'Dark mode', 'Light mode'),
  ('technology', null, 'Cloud storage', 'Local storage'),
  ('technology', null, 'Google Drive', 'Dropbox'),
  ('technology', null, 'Instagram', 'TikTok'),
  ('technology', null, 'Twitter/X', 'Threads'),
  ('technology', null, 'Facebook', 'Instagram'),
  ('technology', null, 'WhatsApp', 'Telegram'),
  ('technology', null, 'Snapchat', 'Instagram Stories'),
  ('technology', null, 'YouTube', 'TikTok'),
  ('technology', null, 'Gaming PC', 'Gaming console'),
  ('technology', null, 'Wireless charging', 'Cable charging'),
  ('technology', null, 'USB-C', 'Lightning'),
  ('technology', null, 'Foldable phone', 'Regular phone'),
  ('technology', null, 'Big phone screen', 'Compact phone'),
  ('technology', null, 'Notifications on', 'Do not disturb always'),
  ('technology', null, 'New phone every year', 'Keep it until it breaks'),
  ('technology', null, 'Buy the latest model', 'Wait for the price drop'),
  ('technology', null, 'Smart home devices', 'Manual control'),
  ('technology', null, 'Alexa', 'Google Assistant'),
  ('technology', null, 'E-reader', 'Physical books'),
  ('technology', null, 'Kindle', 'Physical library'),
  ('technology', null, 'Typing on phone', 'Typing on laptop'),
  ('technology', null, 'Voice notes', 'Text messages'),
  ('technology', null, 'Video calls', 'Phone calls'),
  ('technology', null, 'Zoom', 'Google Meet'),
  ('technology', null, 'Slack', 'Microsoft Teams'),
  ('technology', null, 'Notion', 'Google Docs'),
  ('technology', null, 'Figma', 'Adobe XD'),
  ('technology', null, 'VS Code', 'JetBrains IDEs'),
  ('technology', null, 'Python', 'JavaScript'),
  ('technology', null, 'iOS App Store', 'Google Play Store'),
  ('technology', null, '5G', 'Wi-Fi'),
  ('technology', null, 'Bluetooth speaker', 'Wired speaker'),
  ('technology', null, 'Drone photography', 'Handheld camera'),
  ('technology', null, 'DSLR camera', 'Smartphone camera'),
  ('technology', null, 'Streaming console games', 'Downloading games'),
  ('technology', null, 'Crypto', 'Traditional banking'),
  ('technology', null, 'Mobile money', 'Cash'),
  ('technology', null, 'Online banking', 'Branch banking'),
  ('technology', null, 'Biometric login', 'Password login'),
  ('technology', null, 'Face ID', 'Fingerprint ID'),
  ('technology', null, 'Minimalist home screen', 'App-packed home screen'),
  ('technology', null, 'Widgets everywhere', 'Clean simple layout'),
  ('technology', null, 'Public Wi-Fi', 'Mobile data'),
  ('technology', null, 'Self-checkout', 'Cashier'),
  ('technology', null, 'Smart TV', 'Regular TV with a streaming box'),
  ('technology', null, 'Robot vacuum', 'Manual cleaning'),
  ('technology', null, 'Electric toothbrush', 'Manual toothbrush'),
  ('technology', null, 'Fitness tracker', 'No tracker, just intuition'),
  ('technology', null, 'Read the manual', 'Figure it out yourself'),
  ('technology', null, 'Early adopter', 'Wait and see'),
  ('technology', null, 'Open source software', 'Proprietary software'),
  ('technology', null, 'Remote work', 'Office work'),
  ('technology', null, 'Multiple monitors', 'Single screen focus'),
  ('technology', null, 'Mechanical keyboard', 'Membrane keyboard')
;

insert into public.comparisons (id, category_id, prompt, is_onboarding, status)
select s.id, c.id, s.prompt, false, 'active'
from _seed_0008 s
join public.categories c on c.slug = s.category_slug;

insert into public.comparison_options (comparison_id, side, label)
select id, 'a', option_a from _seed_0008
union all
select id, 'b', option_b from _seed_0008;
