-- Second wave of catalog content — a fresh batch across all 9 non-trivia
-- categories so the diversified feed (get_feed_order) has enough volume
-- per category to stay varied over many scrolls. Captions generated the
-- same way as migration 0015's backfill.
create temporary table _seed_0028 (
  id uuid not null default gen_random_uuid(),
  category_slug text not null,
  prompt text,
  option_a text not null,
  option_b text not null
) on commit drop;

insert into _seed_0028 (category_slug, prompt, option_a, option_b) values
  ('music', null, 'Billie Eilish', 'Olivia Rodrigo'),
  ('music', null, 'The Weeknd', 'Drake'),
  ('music', null, 'Ariana Grande', 'Dua Lipa'),
  ('music', null, 'Post Malone', 'Travis Scott'),
  ('music', null, 'Doja Cat', 'Nicki Minaj'),
  ('music', null, 'Stray Kids', 'Seventeen'),
  ('music', null, 'NewJeans', 'IVE'),
  ('music', null, 'Peso Pluma', 'Bad Bunny'),
  ('music', null, 'Rema', 'Asake'),
  ('music', null, 'Omah Lay', 'Fireboy DML'),
  ('music', null, 'Vinyl collector', 'Digital hoarder'),
  ('music', null, 'Concert mosh pit', 'VIP seated section'),
  ('music', null, 'Freestyle rap battles', 'Written verses'),
  ('music', null, 'Music production', 'Songwriting'),
  ('music', null, 'Sampling old records', 'Original instrumentals'),
  ('music', null, 'Boy band era', 'Girl group era'),
  ('music', null, 'Grunge', 'Punk rock'),
  ('music', null, 'Salsa', 'Bachata'),
  ('music', null, 'Afrobeat legends', 'Afrobeats newcomers'),
  ('music', null, 'Live band', 'DJ set'),
  ('cars', null, 'Tesla Model 3', 'BMW i4'),
  ('cars', null, 'Ford F-150', 'Chevy Silverado'),
  ('cars', null, 'Jeep Wrangler', 'Toyota 4Runner'),
  ('cars', null, 'Manual gearbox purist', 'Paddle shifters'),
  ('cars', null, 'Classic muscle car', 'Modern hypercar'),
  ('cars', null, 'Matte wrap', 'Glossy paint'),
  ('cars', null, 'Turbo four-cylinder', 'Naturally aspirated V8'),
  ('cars', null, 'Track day junkie', 'Sunday cruiser'),
  ('cars', null, 'Off-road build', 'Show car build'),
  ('cars', null, 'Lowered suspension', 'Stock ride height'),
  ('cars', null, 'Car meet regular', 'Solo driver'),
  ('cars', null, 'Import tuner', 'American muscle'),
  ('cars', null, 'Convertible top down', 'Sunroof only'),
  ('cars', null, 'Leasing every 3 years', 'Buying and keeping forever'),
  ('cars', null, 'Detailing it yourself', 'Professional detail shop'),
  ('cars', null, 'Aftermarket exhaust', 'Factory tune'),
  ('cars', null, 'Big wheels, low profile tires', 'Smaller wheels, more sidewall'),
  ('cars', null, 'EV road trip planning', 'Gas station convenience'),
  ('cars', null, 'Dashcam always on', 'No dashcam'),
  ('cars', null, 'Car insurance bundle', 'Pay-per-mile insurance'),
  ('fashion', null, 'Thrifted fits', 'Fast fashion hauls'),
  ('fashion', null, 'Oversized streetwear', 'Tailored fits'),
  ('fashion', null, 'Sneaker rotation', 'One reliable pair'),
  ('fashion', null, 'Bold prints', 'Monochrome minimalism'),
  ('fashion', null, 'Luxury logos', 'Quiet luxury'),
  ('fashion', null, 'Statement jewelry', 'Understated accessories'),
  ('fashion', null, 'Custom tailoring', 'Off the rack'),
  ('fashion', null, 'Vintage denim', 'New raw denim'),
  ('fashion', null, 'Designer bag investment', 'Rotating cheaper bags'),
  ('fashion', null, 'Street style icon', 'Runway purist'),
  ('fashion', null, 'Layered accessories', 'One statement piece'),
  ('fashion', null, 'Seasonal wardrobe refresh', 'Capsule wardrobe forever'),
  ('fashion', null, 'Bold lip color', 'Natural makeup'),
  ('fashion', null, 'Platform shoes', 'Flats always'),
  ('fashion', null, 'Y2K revival', 'Modern minimalist'),
  ('fashion', null, 'Matching sets', 'Mix and match separates'),
  ('fashion', null, 'Statement outerwear', 'Basic layering pieces'),
  ('fashion', null, 'Handmade jewelry', 'Designer brand jewelry'),
  ('fashion', null, 'Bold hair color', 'Natural hair color'),
  ('fashion', null, 'Fragrance layering', 'One signature scent'),
  ('travel', null, 'Backpacking Southeast Asia', 'Luxury resort in the Maldives'),
  ('travel', null, 'Solo road trip', 'Group tour bus'),
  ('travel', null, 'Camping under the stars', 'Boutique hotel stay'),
  ('travel', null, 'Cruise ship vacation', 'Overland adventure'),
  ('travel', null, 'Iceland in winter', 'Iceland in summer'),
  ('travel', null, 'Japan cherry blossom season', 'Japan autumn leaves'),
  ('travel', null, 'All-inclusive resort', 'Airbnb local stay'),
  ('travel', null, 'Traveling with a full itinerary', 'Winging it completely'),
  ('travel', null, 'Learning basic phrases', 'Relying on translation apps'),
  ('travel', null, 'Street food adventures', 'Sit-down restaurant reviews'),
  ('travel', null, 'Beach destination', 'Mountain destination'),
  ('travel', null, 'City hopping', 'One city deep dive'),
  ('travel', null, 'Traveling light with carry-on', 'Packing every scenario'),
  ('travel', null, 'Solo female travel', 'Traveling in a group'),
  ('travel', null, 'Volunteering abroad', 'Pure leisure travel'),
  ('travel', null, 'Digital nomad life', 'Home base with vacations'),
  ('travel', null, 'Overnight train', 'Short-haul flight'),
  ('travel', null, 'Travel journal', 'Photos as memories'),
  ('travel', null, 'Bucket list checklist', 'Repeat your favorite place'),
  ('travel', null, 'Passport stamps collector', 'Frequent flyer miles collector'),
  ('technology', null, 'ChatGPT', 'Google Gemini'),
  ('technology', null, 'MacBook', 'Windows laptop'),
  ('technology', null, 'iPhone', 'Samsung Galaxy'),
  ('technology', null, 'AirPods', 'Wired earphones'),
  ('technology', null, 'Smart ring', 'Smartwatch'),
  ('technology', null, 'Cloud storage', 'Local hard drive'),
  ('technology', null, 'No-code tools', 'Learning to code'),
  ('technology', null, 'Foldable phone', 'Regular phone'),
  ('technology', null, 'AI-generated art', 'Hand-drawn art'),
  ('technology', null, 'Voice assistants', 'Typing everything manually'),
  ('technology', null, 'Dark mode everything', 'Light mode everything'),
  ('technology', null, 'Password manager', 'Memorizing passwords'),
  ('technology', null, 'Smart home automation', 'Manual light switches'),
  ('technology', null, 'E-book reader', 'Physical books'),
  ('technology', null, 'Streaming everything', 'Owning digital copies'),
  ('technology', null, 'VR headset gaming', 'Flat screen gaming'),
  ('technology', null, 'Open-source software', 'Paid premium software'),
  ('technology', null, 'Building your own PC', 'Buying pre-built'),
  ('technology', null, 'Multiple browser tabs forever', 'Closing tabs as you go'),
  ('technology', null, 'Two-factor authentication always', 'Just a password'),
  ('food', null, 'Homemade pasta', 'Store-bought pasta'),
  ('food', null, 'Street tacos', 'Sit-down Mexican restaurant'),
  ('food', null, 'Spicy ramen', 'Mild ramen'),
  ('food', null, 'Air fryer everything', 'Oven baked'),
  ('food', null, 'Meal prepping Sundays', 'Cooking fresh daily'),
  ('food', null, 'Brunch culture', 'Skip breakfast entirely'),
  ('food', null, 'Dessert first', 'Save dessert for last'),
  ('food', null, 'Homemade jollof', 'Restaurant jollof'),
  ('food', null, 'Grilled suya', 'Peppered snail'),
  ('food', null, 'Bubble tea', 'Fresh juice'),
  ('food', null, 'Fine dining tasting menu', 'Casual comfort food'),
  ('food', null, 'Cooking from scratch', 'Meal kit delivery'),
  ('food', null, 'Extra spicy pepper sauce', 'Mild seasoning'),
  ('food', null, 'Buffet style', 'Plated courses'),
  ('food', null, 'Farmers market produce', 'Supermarket produce'),
  ('food', null, 'Grilled fish and plantain', 'Fried rice and chicken'),
  ('food', null, 'Homemade smoothies', 'Store-bought smoothies'),
  ('food', null, 'Late night snacks', 'No eating after 8pm'),
  ('food', null, 'Cooking by instinct', 'Following the recipe exactly'),
  ('food', null, 'Food truck finds', 'Michelin-starred restaurant'),
  ('movies', null, 'Dune', 'Interstellar'),
  ('movies', null, 'Oppenheimer', 'Barbie'),
  ('movies', null, 'Marvel movies', 'DC movies'),
  ('movies', null, 'Studio Ghibli', 'Pixar'),
  ('movies', null, 'Slow-burn drama', 'Fast-paced action'),
  ('movies', null, 'Subtitled foreign films', 'Dubbed foreign films'),
  ('movies', null, 'Movie theater experience', 'Home theater setup'),
  ('movies', null, 'Plot twist endings', 'Predictable happy endings'),
  ('movies', null, 'Practical effects', 'CGI-heavy films'),
  ('movies', null, 'Nollywood dramas', 'Bollywood musicals'),
  ('movies', null, 'True crime documentaries', 'Nature documentaries'),
  ('movies', null, 'Rewatching favorites', 'Always something new'),
  ('movies', null, 'Reading reviews before watching', 'Going in blind'),
  ('movies', null, 'Long epic trilogies', 'Standalone films'),
  ('movies', null, 'Villain steals the show', 'Hero steals the show'),
  ('movies', null, 'Musicals', 'Straight drama'),
  ('movies', null, 'Book adaptation purist', 'Movie stands on its own'),
  ('movies', null, 'Opening weekend viewing', 'Waiting for streaming'),
  ('movies', null, 'Popcorn and candy', 'Nachos and soda'),
  ('movies', null, 'Director''s cut', 'Theatrical cut'),
  ('sports', null, 'Messi', 'Ronaldo'),
  ('sports', null, 'Real Madrid', 'Barcelona'),
  ('sports', null, 'NBA', 'EuroLeague basketball'),
  ('sports', null, 'Boxing', 'MMA'),
  ('sports', null, 'Formula 1', 'MotoGP'),
  ('sports', null, 'Home stadium atmosphere', 'Watching on TV with friends'),
  ('sports', null, 'Fantasy football manager', 'Casual fan'),
  ('sports', null, 'Underdog story', 'Dynasty team'),
  ('sports', null, 'Sports betting', 'Watching without betting'),
  ('sports', null, 'College sports rivalry', 'Professional league loyalty'),
  ('sports', null, 'Marathon running', 'Sprint training'),
  ('sports', null, 'Team sport camaraderie', 'Individual sport focus'),
  ('sports', null, 'Coach''s tactics', 'Individual brilliance'),
  ('sports', null, 'Off-season transfer rumors', 'In-season only'),
  ('sports', null, 'National team pride', 'Club team loyalty'),
  ('sports', null, 'Olympics every four years', 'World Cup every four years'),
  ('sports', null, 'Sports documentaries', 'Sports talk shows'),
  ('sports', null, 'Youth academies', 'Big-money transfers'),
  ('sports', null, 'Playing pickup games', 'Watching from the couch'),
  ('sports', null, 'Home advantage', 'Away day loyalty'),
  ('gaming', null, 'Elden Ring', 'Baldur''s Gate 3'),
  ('gaming', null, 'Call of Duty', 'Battlefield'),
  ('gaming', null, 'Minecraft', 'Roblox'),
  ('gaming', null, 'PlayStation 5', 'Xbox Series X'),
  ('gaming', null, 'Nintendo Switch', 'Steam Deck'),
  ('gaming', null, 'Speedrunning', 'Completionist 100%'),
  ('gaming', null, 'Solo campaign', 'Co-op with friends'),
  ('gaming', null, 'Retro pixel art games', 'Photorealistic AAA titles'),
  ('gaming', null, 'Mobile gaming', 'Handheld console gaming'),
  ('gaming', null, 'Ranked competitive', 'Casual matches'),
  ('gaming', null, 'Modding your games', 'Playing vanilla'),
  ('gaming', null, 'Physical game collection', 'All-digital library'),
  ('gaming', null, 'Streaming your gameplay', 'Playing privately'),
  ('gaming', null, 'Turn-based strategy', 'Real-time action'),
  ('gaming', null, 'Building the ultimate PC rig', 'Console simplicity'),
  ('gaming', null, 'Boss rush difficulty', 'Story mode easy'),
  ('gaming', null, 'Open world exploration', 'Linear guided campaign'),
  ('gaming', null, 'Esports fan', 'Casual player only'),
  ('gaming', null, 'New release day one', 'Waiting for reviews'),
  ('gaming', null, 'Gacha games', 'Premium one-time purchase games')
;

insert into public.comparisons (id, category_id, prompt, caption, creator_id, is_onboarding, status)
select
  s.id,
  c.id,
  s.prompt,
  (array[
    'Which one wins? #thisorthat #pickaside',
    'Everyone has an opinion on this one. #debate',
    'Drop your pick below. #vote #hottake',
    'The eternal debate continues. #thisorthat',
    'No wrong answers, just vibes. #pickone',
    'Settle it in the comments. #thisorthat #vote'
  ])[1 + (row_number() over (order by s.id) % 6)],
  (select id from public.profiles where is_seed_account = true order by md5(s.id::text || id::text) limit 1),
  false,
  'active'
from _seed_0028 s
join public.categories c on c.slug = s.category_slug;

insert into public.comparison_options (comparison_id, side, label)
select id, 'a', option_a from _seed_0028
union all
select id, 'b', option_b from _seed_0028;
